// 03_vue/src/App.vue
<template>
    <div :class="['main', themeBlack ? 'black' : 'white']">Hello World!</div>
    <br />
    <button @click="toggleTheme">toggle theme</button>
</template>

<script setup>
import {ref} from 'vue'

const themeBlack = ref(false)
const toggleTheme = () => themeBlack.value = !themeBlack.value
</script>

<style>
.main {
    display: inline-block;
    padding: 10px 12px;
}
.black {
    background: #000;
    color: #fff;
}
.white {
    background: #ddd;
    color: #000;
}

button {
    display: inline-block;
    margin-top: 20px;
    border: 1px solid #eaeaea;
    border-radius: 2px;
    padding: 4px 6px;
    background: #fff;
    color: #000;
}

button:hover {
    background: #eaeaea;
}
</style>

// 04_react/src/App.jsx
import React, { useState } from 'react';
import './index.css';

const Component = () => {
    const [themeBlack, setTheme] = useState(false);

    const toggleTheme = () => {
        setTheme(!themeBlack);
    };
    return (
        <div>
            <div className={`main ${themeBlack ? 'black' : 'white'}`}>Hello World!</div>
            <br />
            <button onClick={toggleTheme}>toggle theme</button>
        </div>
    );
};

export default Component;
